# Generated by Django 5.2 on 2025-09-06 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_imge', models.ImageField(null=True, upload_to='')),
                ('user_email', models.EmailField(max_length=254, null=True)),
                ('shared_notes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
