# Generated by Django 5.2 on 2025-09-07 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userinfos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('RD', 'Readable'), ('WR', 'Writable')], max_length=2)),
                ('date', models.DateTimeField()),
                ('notes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.notes')),
                ('share_from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_form_me', to=settings.AUTH_USER_MODEL)),
                ('share_to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_to_me', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
