# Generated by Django 5.2 on 2025-09-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sharednotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharednotes',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('DS', 'Disable')], default='AC', max_length=2),
        ),
    ]
