# Generated by Django 5.2 on 2025-09-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sharednotes_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notes_images'),
        ),
    ]
