# Generated by Django 5.2.5 on 2025-11-09 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_notes_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharednotes',
            name='share_from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharednotes',
            name='share_to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
